// // Immediately Invoked Function Expressions (IIFE)


// (function chai(){
//     // named IIFE
//     console.log(`DB CONNECTED`);
// })(); // when we write 2 iife functions we have to write ; after execution bracket of 1st iife function, for breaking the 1st iife function cause if we don't do this our code can throw error.

// ( (name) => {
//     console.log(`DB CONNECTED TWO ${name}`);
// } )('hitesh')